"""US-003, 006, 007, 008, 009 : aide ID, modification, suppression, reprise v1, temps du club."""
import sys, threading, http.server, functools, os, json
from playwright.sync_api import sync_playwright
from helpers import ROOT, OUT, TESTS_DIR, start_server
srv, URL = start_server()
ok = 0
def check(cond, label):
    global ok
    if not cond: raise AssertionError(label)
    ok += 1; print('  ✓', label)
P = {'name': 'Ava Hehlen', 'swimrankingsId': '5332548', 'gender': 'F', 'birthYear': '2010', 'club': 'Lausanne Aquatique', 'createdAt': '2026-01-01T00:00:00Z'}
V1 = {'id': 5332548, 'fullName': 'Ava Hehlen', 'firstName': 'Ava', 'lastName': 'Hehlen', 'gender': 'Female', 'yearOfBirth': 2010, 'club': 'Lausanne Aquatique', 'nation': 'SUI', 'personalBests': []}
all_errors = []
def new_page(ctx, storage=None, width=375, extra=''):
    page = ctx.new_page(); page.set_viewport_size({'width': width, 'height': 812})
    for n in ('swimmers-data.json', 'swimmers-season.json'):
        page.route(f'**/raw.githubusercontent.com/**/{n}', lambda r, req, n=n: r.fulfill(path=os.path.join(ROOT, n)))
    init = 'localStorage.clear();' + ''.join(f'localStorage.setItem({json.dumps(k)}, {json.dumps(v if isinstance(v, str) else json.dumps(v))});' for k, v in (storage or {}).items())
    page.add_init_script(f"if (!sessionStorage.getItem('init')) {{ sessionStorage.setItem('init', '1'); {init} }}" + extra)
    page.on('pageerror', lambda e: all_errors.append(str(e)))
    page.goto(URL); page.wait_for_timeout(300)
    return page
stored = lambda pg, key='swimtimes_profile': pg.evaluate(f"localStorage.getItem({json.dumps(key)})")
active = lambda pg: pg.evaluate('document.activeElement.id || document.activeElement.className')

with sync_playwright() as p:
    b = p.chromium.launch(); ctx = b.new_context()

    print('US-006 : modification du profil')
    page = new_page(ctx, {'swimtimes_profile': P, 'swimtimes_pb': '{"data":[]}', 'swimtimes_season': '{"data":[]}'})
    page.wait_for_function("swimmerDataStatus === 'loaded'")
    page.click('#header-settings'); page.click('text=Modifier le profil')
    check(page.locator('#profile-back').is_visible() and page.locator('.setup-title').inner_text() == 'Modifier le profil', 'titre « Modifier le profil » et bouton ←')
    check(page.locator('#profile-cancel').is_visible() and active(page) == 'setup-title', 'bouton Annuler, focus sur le titre')
    check(page.locator('#profile-name').input_value() == 'Ava Hehlen' and page.locator('input[value=F]').is_checked(), 'formulaire pré-rempli')
    submit = page.locator('#profile-submit')
    check(submit.is_disabled(), 'Enregistrer inactif tant que rien ne change')
    page.fill('#profile-club', 'Red Fish'); check(submit.is_enabled(), 'actif après une modification')
    page.fill('#profile-club', 'Lausanne Aquatique'); check(submit.is_disabled(), 'inactif si on revient aux valeurs d\'origine')
    page.fill('#profile-name', 'Ava Test'); page.keyboard.press('Escape'); page.wait_for_selector('#confirm-dialog[open]'); page.wait_for_selector('#confirm-ok:enabled'); page.click('#confirm-ok')
    check(page.locator('#settings-screen').is_visible() and json.loads(stored(page))['name'] == 'Ava Hehlen', 'Échap annule sans enregistrer')
    page.click('text=Modifier le profil'); page.fill('#profile-name', 'Ava Test'); page.click('#profile-back'); page.wait_for_selector('#confirm-dialog[open]'); page.wait_for_selector('#confirm-ok:enabled'); page.click('#confirm-ok')
    check(page.locator('#settings-screen').is_visible() and json.loads(stored(page))['name'] == 'Ava Hehlen', '← annule sans enregistrer')
    page.click('text=Modifier le profil'); page.fill('#profile-name', '')
    page.click('#profile-submit')
    check(page.locator('#profile-name-error').is_visible(), 'mêmes validations qu\'à la création')
    page.fill('#profile-name', 'Bea Martin')
    warn = page.locator('#profile-swimrankingsId-warning')
    check(not warn.is_visible(), 'pas d\'avertissement si l\'ID ne change pas')
    page.fill('#profile-swimrankingsId', '5284006')
    check(warn.is_visible() and 'ancien ID' in warn.inner_text(), 'avertissement si l\'ID change')
    page.fill('#profile-swimrankingsId', '5332548'); check(not warn.is_visible(), 'avertissement retiré si on remet l\'ID')
    page.fill('#profile-swimrankingsId', '5284006'); page.click('#profile-submit')
    page.wait_for_selector('#settings-screen .btn-back', state='visible')
    check('Profil mis à jour' in page.locator('#toast').inner_text(), 'toast « Profil mis à jour »')
    saved = json.loads(stored(page))
    check(saved['name'] == 'Bea Martin' and saved['createdAt'] == P['createdAt'] and saved['updatedAt'], 'enregistré, createdAt conservé, updatedAt mis à jour')
    check(stored(page, 'swimtimes_pb') is None and stored(page, 'swimtimes_season') is None, 'temps de l\'ancien ID supprimés')
    check(page.locator('#header-avatar').inner_text() == 'BM', 'initiales du header à jour')
    page.click('.btn-back'); page.click('#header-avatar')
    check('Bea Martin' in page.locator('#swimmer-popup').inner_text() and '5284006' in page.locator('#swimmer-popup').inner_text(), 'popup à jour')
    page.keyboard.press('Escape')
    page.click('#header-settings'); page.click('text=Modifier le profil'); page.fill('#profile-club', 'X'); page.click('#profile-submit')
    page.wait_for_selector('#settings-screen .btn-back', state='visible')
    check(json.loads(stored(page))['swimrankingsId'] == '5284006', 'ID inchangé : temps conservés (pas de suppression inutile)')
    page.wait_for_timeout(400); page.screenshot(path=f'{OUT}/rest-edit.png')

    print('US-007 : suppression des données')
    page = new_page(ctx, {'swimtimes_profile': P, 'swimtimes_pb': '{}', 'swimtimes_season': '{}', 'swimmer_profile': V1, 'athlete_id': '5332548', 'autre_app': 'garde'})
    page.wait_for_selector('.nav', state='visible'); page.click('#header-settings')
    page.click('#settings-delete')
    dialog = page.locator('#confirm-dialog')
    check(dialog.is_visible() and 'irréversible' in dialog.inner_text() and 'supprimés de cet appareil' in dialog.inner_text(), 'confirmation avec texte explicite')
    check(active(page) == 'confirm-cancel', 'focus sur Annuler (choix sûr)')
    page.wait_for_timeout(300); page.screenshot(path=f'{OUT}/rest-delete.png')
    ids = []
    for _ in range(5):
        page.keyboard.press('Tab'); ids.append(active(page))
    page.keyboard.press('Shift+Tab'); ids.append(active(page))
    check(set(ids) <= {'confirm-cancel', 'confirm-ok'}, f'focus piégé dans la confirmation {ids}')
    page.keyboard.press('Escape')
    check(not dialog.is_visible() and page.locator('#settings-screen').is_visible() and stored(page) is not None, 'Échap : rien supprimé, Paramètres toujours ouverts')
    check(active(page) == 'settings-delete', 'focus rendu au bouton Supprimer')
    page.click('#settings-delete'); page.wait_for_timeout(450); page.click('#confirm-cancel')
    check(not dialog.is_visible() and stored(page) is not None, 'Annuler : rien supprimé')
    page.click('#settings-delete'); page.wait_for_selector('#confirm-dialog[open]'); page.wait_for_selector('#confirm-ok:enabled'); page.click('#confirm-ok')
    page.wait_for_selector('#profile-form')
    keys = page.evaluate('Object.keys(localStorage)')
    check(keys == ['autre_app'], f'clés SwimTimes et v1 supprimées, le reste conservé {keys}')
    check(not page.locator('.nav').is_visible() and not page.locator('.header-actions').is_visible() and not page.locator('#settings-screen').is_visible(), 'écran de configuration initial')
    check(page.locator('#profile-name').input_value() == '' and page.locator('.notice').count() == 0, 'formulaire vierge (pas de reprise v1)')
    check(active(page) == 'setup-heading' and 'supprimées' in page.locator('#toast').inner_text(), 'focus sur le titre, toast de confirmation')
    page.fill('#profile-name', 'Léa Dupont'); page.fill('#profile-swimrankingsId', '5332548'); page.click('text=Femme'); page.click('#profile-submit')
    page.wait_for_selector('.nav', state='visible')
    check(page.locator('#header-avatar').inner_text() == 'LD', 'nouveau profil créé après suppression')

    page = new_page(ctx, {'swimtimes_profile': P}, extra="Storage.prototype.removeItem = function(){ throw new DOMException('bloqué', 'SecurityError') };")
    page.wait_for_selector('.nav', state='visible'); page.click('#header-settings'); page.click('#settings-delete'); page.wait_for_selector('#confirm-dialog[open]'); page.wait_for_selector('#confirm-ok:enabled'); page.click('#confirm-ok')
    check(page.locator('#confirm-dialog').is_visible() and 'Impossible de supprimer' in page.locator('#confirm-error').inner_text(), 'stockage bloqué : erreur dans la confirmation, rien ne change')

    print('US-008 : reprise du profil v1')
    page = new_page(ctx, {'swimmer_profile': V1, 'athlete_id': '5332548'})
    page.wait_for_selector('#profile-form')
    page.wait_for_function("document.getElementById('profile-notice').textContent"); check('On a retrouvé ton profil' in page.locator('.notice').inner_text(), 'message « On a retrouvé ton profil »')
    vals = [page.locator(f'#profile-{k}').input_value() for k in ('name', 'swimrankingsId', 'birthYear', 'club')]
    check(vals == ['Ava Hehlen', '5332548', '2010', 'Lausanne Aquatique'] and page.locator('input[value=F]').is_checked(), f'pré-rempli depuis la v1 {vals}')
    check(page.locator('.field-error:visible').count() == 0, 'aucune erreur pour un profil v1 complet')
    page.wait_for_timeout(300); page.screenshot(path=f'{OUT}/rest-v1.png', full_page=True)
    page.click('#profile-submit'); page.wait_for_selector('.nav', state='visible')
    v2 = json.loads(stored(page))
    check(v2['name'] == 'Ava Hehlen' and v2['swimrankingsId'] == '5332548' and v2['gender'] == 'F', 'profil v2 créé')
    check(stored(page, 'swimmer_profile') is None and stored(page, 'athlete_id') is None, 'clés v1 supprimées')

    page = new_page(ctx, {'swimmer_profile': V1, 'athlete_id': '5332548'})
    page.wait_for_selector('#profile-form'); page.click('#profile-reset'); page.wait_for_selector('#confirm-dialog[open]'); page.wait_for_selector('#confirm-ok:enabled'); page.click('#confirm-ok')
    check(page.locator('#profile-name').input_value() == '' and page.locator('#profile-club').input_value() == 'Lausanne Aquatique' and page.locator('.notice').count() == 0, 'Repartir de zéro : formulaire vierge')
    check(stored(page, 'swimmer_profile') is None and stored(page, 'athlete_id') is None and active(page) == 'setup-heading', 'clés v1 supprimées, focus sur le titre')

    for raw in ('{pas du json', '[]', '"texte"', '{}'):
        page = new_page(ctx, {'swimmer_profile': raw})
        page.wait_for_selector('#profile-form')
        check(page.locator('.notice').count() == 0 and page.locator('#profile-name').input_value() == '', f'v1 corrompu {raw!r} : formulaire vierge, sans erreur')

    page = new_page(ctx, {'swimmer_profile': {k: v for k, v in V1.items() if k != 'gender'}})
    page.wait_for_selector('#profile-form')
    check(page.locator('#profile-gender-error').is_visible() and page.evaluate("document.activeElement.name") == 'gender', 'v1 sans genre : erreur et focus sur le genre')
    page = new_page(ctx, {'swimmer_profile': {'id': 5332548}, 'athlete_id': '5332548'})
    page.wait_for_selector('#profile-form')
    check(page.locator('#profile-swimrankingsId').input_value() == '5332548' and page.locator('#profile-name-error').is_visible(), 'v1 partiel : ID repris, nom à compléter')
    page = new_page(ctx, {'swimtimes_profile': {**P, 'gender': 'X'}, 'swimmer_profile': V1})
    page.wait_for_selector('#profile-form')
    page.wait_for_function("document.getElementById('profile-notice').textContent"); check('incomplet' in page.locator('.notice').inner_text(), 'profil v2 invalide prioritaire sur la v1')

    print('US-003 : aide pour l\'ID')
    page = new_page(ctx); page.wait_for_selector('#profile-form')
    toggle = page.locator('#profile-id-help-toggle'); help = page.locator('#profile-id-help')
    check(toggle.is_visible() and 'Comment trouver mon ID' in toggle.inner_text() and not help.is_visible(), 'lien sous le champ ID, aide repliée')
    page.fill('#profile-name', 'Léa'); page.fill('#profile-swimrankingsId', '12')
    toggle.click()
    check(help.is_visible() and toggle.get_attribute('aria-expanded') == 'true', 'aide dépliée')
    t = help.inner_text()
    check('swimrankings.net' in t and 'athleteId=' in t and '5332548' in t, 'étapes et exemple')
    check(help.locator('a').get_attribute('target') == '_blank' and 'noopener' in help.locator('a').get_attribute('rel'), 'lien externe dans un nouvel onglet')
    check(page.locator('#profile-name').input_value() == 'Léa' and page.locator('#profile-swimrankingsId').input_value() == '12', 'saisie conservée')
    page.wait_for_timeout(300); page.screenshot(path=f'{OUT}/rest-help.png', full_page=True)
    toggle.click(); check(not help.is_visible() and toggle.get_attribute('aria-expanded') == 'false', 'aide repliée au 2e clic')
    page.fill('#profile-swimrankingsId', 'https://www.swimrankings.net/index.php?page=athleteDetail&athleteId=5332548&pbest=2027')
    check(page.locator('#profile-swimrankingsId').input_value() == '5332548', 'ID extrait de l\'adresse collée')
    check('extrait' in page.locator('#profile-swimrankingsId-status').inner_text(), 'message « ID extrait » annoncé')
    page.locator('#profile-swimrankingsId').blur(); check(not page.locator('#profile-swimrankingsId-error').is_visible(), 'ID extrait valide')
    page.fill('#profile-swimrankingsId', 'https://www.swimrankings.net/index.php?page=home'); page.locator('#profile-swimrankingsId').blur()
    check(page.locator('#profile-swimrankingsId-error').is_visible(), 'adresse sans athleteId : erreur')
    page.fill('#profile-swimrankingsId', '12345678901'); page.locator('#profile-swimrankingsId').blur()
    check('10 au maximum' in page.locator('#profile-swimrankingsId-error').inner_text(), 'ID de plus de 10 chiffres refusé')

    print('US-009 : temps pendant la transition')
    page = new_page(ctx, {'swimtimes_profile': {**P, 'name': 'Nom Du Profil', 'club': 'Club Du Profil'}})
    page.wait_for_function("swimmerDataStatus === 'loaded'")
    check('PB:' in page.locator('#pb-time').inner_text(), 'PB affichés depuis swimmers-data.json')
    page.click('.nav-tab[data-tab=progress]'); check(page.locator('.progress-card').count() == 3, 'Progression affichée')
    page.click('#header-avatar'); t = page.locator('#swimmer-popup').inner_text()
    check('Nom Du Profil' in t and 'Club Du Profil' in t, 'nom et club issus du profil, pas du JSON')
    page = new_page(ctx, {'swimtimes_profile': {**P, 'swimrankingsId': '999'}})
    page.wait_for_function("swimmerDataStatus === 'not-found'")
    check('Aucune donnée' in page.locator('#pb-time').inner_text(), 'ID absent : message 6.2')

    check(not all_errors, f'aucune erreur JS {all_errors}')
    b.close()
srv.shutdown()
print(f'\n✅ {ok} vérifications OK')
